spring:
  application:
    name: NexusHub
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://jvdtbiqu75jr9t03:li6e3u9myj3aywac@sp6xl8zoyvbumaa2.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/qetwqkiyx7ferfx1?autoReconnect=true&allowPublicKeyRetrieval=true&useSSL=false
    username: jvdtbiqu75jr9t03
    password: li6e3u9myj3aywac
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        database-platform: org.hibernate.dialect.MySQL8Dialect
      database: mysql
      logging:
        level:
          org.springframework.security: DEBUG

server:
  port: 8080